### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by 7loud**
now it's german

### CODE REVIEW

**Comment by brezedc** [comment]
Please remove capitals in the start of words that shouldnt be capitalized. Do that and re-submit :D

**Comment by 7loud** [comment]
Do you mean the beginning of a sentence?

**Comment by brezedc** [comment]
No, you have random words in the middle of sentences starting with capital letters, please make them normal.

**Comment by 7loud** [comment]
These are nouns, they must be capitalized

**Comment by brezedc** [comment]
No, nouns should not be capitalized. No idea where you learnt that.

**Comment by 7loud** [comment]
In German, **all** nouns are capitalized

**Pull request merged**
